### ISSUE TITLE
这个会把json数据零值变成undefined。如{id:0}变成{id:undefined}

### ISSUE THREAD

**Issue by jasonLaw1015** [zyyou/egg-reqp#1]
`function escapeValue(ctx: Context, params: any, key: string) {
  // ctx.logger.warn('params', params, 'key', key);
  if (!params || !params[key]) {
    return undefined;
  }
  return ctx.helper.escape(params[key]);
}`
建议把 !params[key]换成!params.hasOwnProperty(key)这个判断,你有更好的办法更好

**Comment by zyyou** [comment]
感谢，已在1.0.2修复
